// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DecimalJs from "../../node_modules/decimal.js";

function setOptions(prim) {
  DecimalJs.Decimal.set(prim);
  
}

function createDecimal(prim) {
  return new DecimalJs.Decimal(prim);
}

function createDecimalI(prim) {
  return new DecimalJs.Decimal(prim);
}

function createDecimalSt(prim) {
  return new DecimalJs.Decimal(prim);
}

function copyDecimal(prim) {
  return new DecimalJs.Decimal(prim);
}

export {
  setOptions ,
  createDecimal ,
  createDecimalI ,
  createDecimalSt ,
  copyDecimal ,
  
}
/* ../../node_modules/decimal.js Not a pure module */
