// Generated by ReScript, PLEASE EDIT WITH CARE

import DecimalJs from "../../node_modules/decimal.js";

function createDecimal(prim) {
  return new DecimalJs(prim);
}

function createDecimalI(prim) {
  return new DecimalJs(prim);
}

function createDecimalSt(prim) {
  return new DecimalJs(prim);
}

function copyDecimal(prim) {
  return new DecimalJs(prim);
}

export {
  createDecimal ,
  createDecimalI ,
  createDecimalSt ,
  copyDecimal ,
  
}
/* ../../node_modules/decimal.js Not a pure module */
