// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_splice_call from "./../../node_modules/rescript/lib/es6/caml_splice_call.js";
import * as DecimalJs from "../../node_modules/decimal.js";

function setOptions(prim) {
  DecimalJs.Decimal.set(prim);
  
}

function hypot(prim0, prim1) {
  return DecimalJs.Decimal.hypot(prim0, prim1);
}

function hypot3(prim0, prim1, prim2) {
  return DecimalJs.Decimal.hypot(prim0, prim1, prim2);
}

function hypot4(prim0, prim1, prim2, prim3) {
  return DecimalJs.Decimal.hypot(prim0, prim1, prim2, prim3);
}

function hypotArr(prim) {
  return Caml_splice_call.spliceApply(DecimalJs.Decimal.hypot, [prim]);
}

function max(prim0, prim1) {
  return DecimalJs.Decimal.max(prim0, prim1);
}

function max3(prim0, prim1, prim2) {
  return DecimalJs.Decimal.max(prim0, prim1, prim2);
}

function max4(prim0, prim1, prim2, prim3) {
  return DecimalJs.Decimal.max(prim0, prim1, prim2, prim3);
}

function maxArr(prim) {
  return Caml_splice_call.spliceApply(DecimalJs.Decimal.max, [prim]);
}

function min(prim0, prim1) {
  return DecimalJs.Decimal.min(prim0, prim1);
}

function min3(prim0, prim1, prim2) {
  return DecimalJs.Decimal.min(prim0, prim1, prim2);
}

function min4(prim0, prim1, prim2, prim3) {
  return DecimalJs.Decimal.min(prim0, prim1, prim2, prim3);
}

function minArr(prim) {
  return Caml_splice_call.spliceApply(DecimalJs.Decimal.min, [prim]);
}

function createDecimal(prim) {
  return new DecimalJs.Decimal(prim);
}

function createDecimalI(prim) {
  return new DecimalJs.Decimal(prim);
}

function createDecimalSt(prim) {
  return new DecimalJs.Decimal(prim);
}

function copyDecimal(prim) {
  return new DecimalJs.Decimal(prim);
}

function toInt(a) {
  return a.round().toNumber() | 0;
}

var _PI = new DecimalJs.Decimal(-1).acos();

export {
  setOptions ,
  hypot ,
  hypot3 ,
  hypot4 ,
  hypotArr ,
  max ,
  max3 ,
  max4 ,
  maxArr ,
  min ,
  min3 ,
  min4 ,
  minArr ,
  createDecimal ,
  createDecimalI ,
  createDecimalSt ,
  copyDecimal ,
  toInt ,
  _PI ,
  
}
/* _PI Not a pure module */
