// Generated by ReScript, PLEASE EDIT WITH CARE

import * as I18next from "../../node_modules/i18next";
import I18nextHttpBackend from "../../node_modules/i18next-http-backend";

var httpApi = I18nextHttpBackend;

function text(prim) {
  return I18next.t(prim);
}

function use(prim) {
  return I18next.use(prim);
}

export {
  httpApi ,
  text ,
  use ,
  
}
/* httpApi Not a pure module */
