// Generated by ReScript, PLEASE EDIT WITH CARE


function add(a, b) {
  return a + b;
}

function sub(a, b) {
  return a - b;
}

function mult(a, b) {
  return a * b;
}

function div(a, b) {
  return a / b;
}

var FloatField = {
  add: add,
  sub: sub,
  mult: mult,
  div: div,
  $$null: 0,
  one: 1
};

export {
  FloatField ,
  
}
/* No side effect */
